version: '3.8'
services:

    # PHP Service
    app:
        build: 
            context: .
            dockerfile: .docker/Dockerfile
        container_name: app
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        env_file: .env
        ports:
            - "8000:8000"
        volumes:
            - ./:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network

# Docker Networks
networks:
    app-network:
        driver: bridge